### ISSUE TITLE
Clarify IP requirement

### ISSUE THREAD

**Issue by Swader** [AuroraDAO/aurad#4]
From the README

> AuraD requires public TCP access to port 8443, and **has limits** on how frequently a node can change IP addresses.

What are those limits?

**Comment by yennieb** [comment]
@Swader generally speaking, we introduce some delay when switching IP addresses, so that DNS can propagate to clients (your node is identified via DNS based on your hot wallet). We try to keep this as low as possible, but you can expect to have your node go offline for a few minutes when switching.

Regarding the limit, there's not a firm number to share but if you're changing IPs more than every hour, something is wrong and could cause issues. Occasional updates are fine.

**Comment by kokleong98** [comment]
It's possible to run more than 1 node (possible another cloud provider) with different public IP per stake? Any penalties on that if I'm trying switch to another cloud provider after the first stake?

**Comment by Swader** [comment]
^ good question.

--
Re @yennieb - My provider in Croatia changes my IP every 24 hours, so should be fine then?
